### ISSUE TITLE
v0.3-SNAPSHOT

### ISSUE THREAD

**Issue by matthiaskoenig** [sbgn/libsbgn#35]
The idea is to create a develop version v0.3 of the specification and library with corresponding documentation. Here we can implement/document the new features.

Currently these are mainly
- annotations (RDF via extension)
- color via render extension

Some things are necessary to get this going
- documentation page wiki (here we should discuss changes)
- continous integration (automatic building, testing, documentation creation, ..., setup travis)

see also #34 and #33

**Comment by matthiaskoenig** [comment]
I put this on the roadmap https://github.com/sbgn/sbgn/wiki/SBGN-ML_Roadmap
and shifted uncovered things to milestone 4.
The idea is to have a fast iteration on the library with the next milestone providing a clean way to deal with RDF Miriam annotations and the whole render issue.

**Comment by fbergmann** [comment]
I think we should get a 0.3 release out there soonish. I'd be fine to have that even without all the thinks you mentioned up top @matthiaskoenig . For a snapshot, i think we would be good now, we should have several for people to start working with it. I'll be working on adding color / rendering stuff. Not sure who'd be doing RDF stuff (not me).

**Comment by matthiaskoenig** [comment]
@fbergmann I agree. Snapshot is good now. Thanks for all the work.
