### ISSUE TITLE
port ant script to maven

### ISSUE THREAD

**Issue by fbergmann** [sbgn/libsbgn#45]
In order to have the library in maven, i registered a repo, so far so good. However, I would like some help of someone that is more familiar with it, to port out ant scripts to maven. I was hoping that ant run could do the trick, but it did not. 

@draeger Andreas could you perhaps jump in here, you must be using it a lot more for jsbml.

**Comment by niko-rodrigue** [comment]
Yes, definitively, following what was done for jsbml-core, it should not be too hard to setup  maven to at least deploy it online.

**Comment by fbergmann** [comment]
this has since been resolved, thanks to @cannin! The latest code base now has a working pom.
