### ISSUE TITLE
Suggestion: Font style property to be exposed via the RenderUtil class

### ISSUE THREAD

**Issue by ibalaur** [sbgn/libsbgn#52]
Currently, there is no exposed functionality for font style, (as there is for font size and font family).

**Comment by ibalaur** [comment]
Actually, the font style information can be accessed from the Style object itself; but, then, why other properties such as font size and font family are also exposed via the RenderUtils.getStyleProperty and they also can be accessed via the Style object?

**Comment by fbergmann** [comment]
Hello Irina, 

I've added what I thought *might be* useful, but since I'm not actually using the library, I don't know what else would be helpful. Since you have write access, please add whatever you would like to add. let me know if you need me to make a new release snapshot. 

best
Frank

**Comment by ibalaur** [comment]
Hello Frank,
Thank you.
Please see the commit: https://github.com/sbgn/libsbgn/commit/3e9fe382c661e2c8046b6d97c0e9cbbf5bf4e1e5
Best wishes,
Irina
